- DH_Engine/Classes/DHATGun.uc
- DH_Weapons/Classes/DH_ATGunRotateWeapon.uc
- System/DarkestHourDev.bat
Helped fix online AT gun rotation issues.
> Feature at rotate

- DH_Engine/Classes/DHATGun.uc
> fixed minor problem with projection. 

- DH_Weapons/Classes/DH_M38Fire.uc
- DH_Weapons/Classes/DH_M44Fire.uc
- DH_Weapons/Classes/DH_MN9130Ammo.uc
- DH_Weapons/Classes/DH_MN9130Fire.uc
Changing ammo icon for mosin nagant to the same that Kar98 uses
> DarklightGames/DarkestHour#1077 fixing mosin nagant HUD ammo icon

- DarkestHourDev/Maps/DH-WIP_Kommerscheidt_Advance.rom
Added a lot more detail and fine tuned the map. Mainly in the form of more static meshes and bether lightning.
> Event version of kommerschiet

- DarkestHourDev/Maps/DH-Armoured_Belgium_Clash.rom
- DarkestHourDev/Maps/DH-Armoured_Eindhoven_Clash.rom
- DarkestHourDev/Maps/DH-Armoured_Panzerschlacht_Clash.rom
The "new" maps are from GG tank server and have been updated by me and Saulniv so they now work with the latest version of the DH. 
Belgium
Panzerschlacht
Eidenhoven
> 3 New Western front maps for the tank server

- DH_Weapons/Classes/DH_MP41Weapon.uc
https://github.com/DarklightGames/DarkestHour/issues/1083
> DarklightGames/DarkestHour#1083 adding semi-automatic fire mode to MP41

- DarkestHourDev/Maps/DH-Armored_Lemberg_Clash.rom
- DarkestHourDev/Maps/DH-Armored_Mickistein_Clash.rom
- DarkestHourDev/Maps/DH-Armored_Oder_Clash.rom
- DarkestHourDev/Maps/DH-Armored_Vieux_Clash.rom
- DarkestHourDev/Maps/DH-WIP_Prussia_Push.rom
- DarkestHourDev/Maps/DH-WIP_St_Marie_du_Mont_Advance.rom
St Marie, changed max axis vehicles to 2/ Razorneck
Lemberg, new small/medium sized tank Russian tank map
Oder, new large tank map with Russians
Mickistein, New large tank map with Russians
Vieux, new large tank map with British
> Prussia, changed the RO Mp41 to the DH Mp41/ Saulniv

- DH_Engine/Classes/DHPawn.uc
- DH_Engine/Classes/DHPawnSoundGroup.uc
Hi,
Here are two instance of **DamageType.Name == 'DHBurningDamageType'** I missed yesterday
> Pull request DamageType.default.bFlaming implementation, day-1 patch

- DarkestHourDev/Maps/DH-Armored_Tank_Clash_At_Bastogne_Advance.rom
Author: WOLFkraut
> Fixed that fall through the map thing from Report a Bug
> Armored Tank Clash at Bastogne

- DarkestHourDev/Maps/DH-Armored_Tank_Clash_At_Bastogne_Advance.rom
- DarkestHourDev/Maps/DH-Hurtgenwald_Advance.rom
Author: WOLFkraut
Converting the level into Advance gamemode
> Hurtgenwald Advance

- DH_Vehicles/Classes/DH_KV1sCannon.uc
- DH_Vehicles/Classes/DH_PantherDCannon.uc
- DH_Vehicles/Classes/DH_PantherDTank.uc
- DH_Vehicles/Classes/DH_PanzerIIIJCannon.uc
- DH_Vehicles/Classes/DH_PanzerIIILCannon.uc
- DH_Vehicles/Classes/DH_T3476Cannon.uc
- DH_Vehicles/Classes/DH_T3485Cannon.uc
- fixed some inaccurate slope values
- reduced (or added, where there was none) "fake" slopes on spherical armor details to a small value
- added comments on these details that they are supposed to be spherical
> armor fixes

- DH_Guns/Classes/DH_Pak40Cannon.uc
- DH_Guns/Classes/DH_Pak40CannonLate.uc
- DH_Guns/Classes/DH_Pak40CannonShellAPCR.uc
- DH_Guns/Classes/DH_ZiS2CannonShell.uc
- DH_Vehicles/Classes/DH_KV1sCannon.uc
- DH_Vehicles/Classes/DH_KV1sCannon_Late.uc
- DH_Vehicles/Classes/DH_T3476CannonShellEarly.uc
- DH_Vehicles/Classes/DH_T3476CannonShellSolid.uc
- DH_Vehicles/Classes/DH_T3476_42Cannon.uc
Added pak40 APCR shell and soviet 76mm solid shell, slightly adjusted other soviet 76mm AP shells
> Newshells1

- DH_Engine/Classes/DHLocalMessage.uc
- DH_Engine/Classes/DHSquadSayMessage.uc
- DH_Engine/Classes/DHVoiceSayMessage.uc
Formatting:
```
[SQUAD] [2] Buddy : foo
[SQUAD LEADER] Friend : bar
[VOICE] [SL] Friend : Follow me!
[VOICE] [A] Guy : Take cover!
```
> Display squad member numbers/roles in chat messages

- DH_Guns/Classes/DH_17PounderGunCannon.uc
- DH_Guns/Classes/DH_45mmM1937GunCannon.uc
- DH_Guns/Classes/DH_AT57Cannon.uc
- DH_Guns/Classes/DH_M5GunCannon.uc
- DH_Guns/Classes/DH_Pak38Cannon.uc
- DH_Guns/Classes/DH_Pak40Cannon.uc
- DH_Guns/Classes/DH_ZiS2Cannon.uc
- DH_Guns/Classes/DH_ZiS3Cannon.uc
- DH_Vehicles/Classes/DH_Marder3MCannon.uc
- DH_Vehicles/Classes/DH_SU76Cannon.uc
- DarkestHourDev/Sounds/DH_Vehicle_Reloads.uax
increased reload time on most AT guns, SU76 and marder by ~0.3-0.9 seconds; made new reload sounds so that reload stages dont "skip"
> Improved reload stages on AT guns

- DarkestHourDev/Maps/DH-Rakowice_Advance.rom
- DarkestHourDev/Maps/DH-Target_Range.rom
Jadore: Updated Target Range to include new vehicles.
> Level updates wolfkraut 2

- DarkestHourDev/Maps/DH-WIP_Black_Day_July_Advance.rom
- tank balance
- moved Woods objectives into the Trenches
> kashash: Updates to Black Day July Advance

- DarkestHourDev/StaticMeshes/DH_Vegetation4_stc.usx
- DarkestHourDev/Textures/DH_Vegetation4_tex.utx
Vegetation_4 Packages with new trees added by Matty
> New trees veg package 4 matty

- DarkestHourDev/Maps/DH-Kriegstadt_Advance.rom
- deleted a clipping static mesh
- changed cull distance on popping object
> Kriegstadt Advance

- DH_Guns/Classes/DH_ZiS3Cannon.uc
- DH_Guns/Classes/DH_ZiS3CannonLate.uc
- DH_Guns/Classes/DH_ZiS3CannonPawnLate.uc
- DH_Guns/Classes/DH_ZiS3FactoryLate.uc
- DH_Guns/Classes/DH_ZiS3FactoryLate_Snow.uc
- DH_Guns/Classes/DH_ZiS3GunLate.uc
- DH_Guns/Classes/DH_ZiS3GunLate_Snow.uc
ZIS-3 gun with APCR; cant be built but can be pre-placed by mappers
> late ZIS-3 with APCR

- DH_Vehicles/Classes/DH_BA64ArmoredCar.uc
apparently bulletproof tires requred to drive at slower speed, so i reduced it
> Reduced ba64's max speed to ~45 km/h

- DarkestHourDev/Maps/DH-Valko_Advance.rom
- fixed another bsp death hole
- fixed the suddenly broken doorways on the first objective
- added back accidentaly removed setup phase boundaries
- lowering respawn times on vehicles
> DH-Valko_Advance

- DarkestHourDev/StaticMeshes/DH_Military_stc.usx
Author: AAZ
- 6 trench variations for easier creation of fortifications
> AAZ: 6 trench variations

- DarkestHourDev/Maps/DH-WIP_Wanne_Advance.rom
Wanne Advance: 
- Fixed Final Objective Volume leaking into nearby areas.
- Fixed staircase which blocked entry to a room on the bottom floor of middle 2 story building in Defensive Perimeter objective.
- Hetzer now unlocks when Woods objective is captured (was Defensive Perimeter).
> Bug Fixes and Minor Tweaks

- DarkestHourDev/Textures/DH_Buildings3_tex.utx
- adding a new 'Buildings' package because the other ones are starting to get overloaded
> DH-Buildings3_tex

- DarkestHourDev/StaticMeshes/DH_NorthAfrica_Vehicles_SM.usx
Accidently slippted this in, it is not neaded at all and are just something I used to get some tanks over to my map
> This file a duplication file

- DarkestHourDev/Maps/DH-Radar_Advance.rom
Downscaled the glider 50% so it is the same size as on Vierville
> Downscaled the glider to correct scale

- DarkestHourDev/Maps/DH-Armored_Voronezh_Clash.rom
> DH-Armored_Voronezh_Clash

- DH_Vehicles/Classes/DH_Marder3MDestroyer_CamoTwo.uc
- DH_Vehicles/Classes/DH_Marder3MDestroyer_SnowPaintedCamo.uc
- DH_Vehicles/Classes/DH_Marder3MDestroyer_SnowSolidWhite.uc
- DH_Vehicles/Classes/DH_Marder3MFactory_SnowPaintedCamo.uc
- DH_Vehicles/Classes/DH_Marder3MFactory_SnowSolidWhite.uc
- DH_Vehicles/Classes/DH_Tiger2BFactory_ArdennesSnow332.uc
- DH_Vehicles/Classes/DH_Tiger2BTank_ArdennesSnow332.uc
- DarkestHourDev/Maps/DH-La_Gleize_Advance.rom
- DarkestHourDev/Textures/DH_VehiclesGE_tex7.utx
- Added new winter paint camo to the Marder 3M, credits to Matty.
- Added new solid whitewash camo to the Marder 3M, credits to GG.
- Added new camo variant of the Marder 3M.
- Created vehicle factories for the Marder and King Tiger snow skins (will not do this again in the future, but these are being used on Celles).
> Added New Tank Skins for the Marder

- DarkestHourDev/StaticMeshes/DH_Vegetation4_stc.usx
- DarkestHourDev/Textures/DH_Vegetation4_tex.utx
3rd times a charm? 
- Added new tree types with proper collision from Matty.
> New Veg 4 Packages from Matty. 

- DH_Engine/Classes/DHGameType_Defence.uc
added timer for when reinfs run out, so that maps cant continue forever because some guy hides in a minefield
> fix for defence game mode

- DarkestHourDev/Maps/DH-Kriegstadt_Advance.rom
- adding some interiors in buildings in front of Kaschade
- restricting Axis constructions in abusable locations
> Kriegstadt

- DH_Guns/Classes/DH_45mmM1937GunCannon.uc
> fixed invisible APCR shells in the early 45mm gun

- DarkestHourDev/Maps/DH-Putot-en-Bessin_Advance.rom
From Kashash: 
Putot en Bessin:
- Added ModifyReinforcementInterval to give the attacking team a good kick start and prevent an early choke game.
> Balance change to Putot.

- DH_Engine/Classes/DHWeapon.uc
- DH_Weapons/Classes/DH_GreaseGunWeapon.uc
- DarkestHourDev/Animations/DH_M3GreaseGun_1st.ukx
- DarkestHourDev/Sounds/DH_WeaponSounds.uax
- DarkestHourDev/Textures/DH_Weapon_tex.utx
Complete overhaul of the M3 Greasegun's first person animations + audio.
This also fixes a bug where the player would be able to interrupt the first-draw animation by ironsighting.
> Greasegun Remake

- DarkestHourDev/Maps/DH-Stavelot_Push.rom
Affects barrel overheating and whatnot.
> Stavelot Push: Set season setting to winter

- DH_Engine/Classes/DHProjectileWeapon.uc
https://discord.com/channels/337666388527153163/337689857717698571/909545770867380305
https://www.youtube.com/watch?v=PhHgajlrRnc
> Fixed the exploit where players could fast-attach bayonet by dropping weapon mid animation

- DarkestHourDev/Textures/DH_Decals.utx
-Added bunch of damaged wall textures, plus some rust ones.
-Includes: bricks, concrete, plaster and rust.
> DH_Decals.utx Update

- DarkestHourDev/Maps/DH-Berezina_Advance.rom
Replaced roammo volumes with dh ammo volumes.
original dh discord report -> https://discord.com/channels/337666388527153163/337689857717698571/940701060945805394
> Berezina_advance qol

- DarkestHourDev/Maps/DH-Hedgerow_Hell_Advance.rom
Added blocking volume in F1 area.
report -> https://discord.com/channels/339838693617565697/339840687698608141/939230202142277652
report with video -> https://discord.com/channels/337666388527153163/337689857717698571/939214520860164138
> Hedgerow-hell-advance-border-fix

- DarkestHourDev/Maps/DH-Smolensk_Advance.rom
fixed stucking in shell holes around bunker cap;
added radio for both sides:
for axis before first cap, for allies before last cap;
added few statics around bunker cap;
moved axis spawn hints in cover after first cap.
> smolensk-advance qol

- DarkestHourDev/Textures/DH_InterfaceArt2_tex.utx
> Removed center point from the Fire marker to make it less obscuring

- DarkestHourDev/StaticMeshes/DH_Landscape.usx
- DarkestHourDev/Textures/DH_Landscape_tex.utx
-Fishing boat by Matty
-Fishing boat beached version
-Small shipwreck by ???
-New pier/dock statics 5 variations tilable
-3 Dead sheep
-Wave textures (used on Dog Green) and moving wave plane
-3x 15 rocks in 3 different textures (desert, grey, snow)
everything should have collision meshes, the right material and in some cases detail textures
> New statics added to DH_Landscape

- DarkestHourDev/Maps/DH-Armored_Kharkov_Advance.rom
- DarkestHourDev/Maps/DH-Les_Champs_de_Losque_Advance.rom
Kharkov Advance:
- Fixed objective progression issue.
Les Champs Advance:
- Fixed missing objective volume for the first cap.
- Added no-rain volume to the new building.
> Hotfix for Kharkov and Les Champs

- DarkestHourDev/Maps/DH-Armored_La_Feuillie_Advance.rom
- DarkestHourDev/Maps/DH-HedgeHog_Push.rom
- DarkestHourDev/Maps/DH-Les_Champs_de_Losque_Advance.rom
- DarkestHourDev/Maps/DH-Rhine_River_Clash.rom
Hedgehog:
- Fixed a bug the Allied spawn.
Les Champs:
- More updates to the first and fourth objective areas.
Rhine River:
- Initial commit with lighting changes.
Armored La Feuillie Advance:
- New map.
> Updates and Fixes to Various Levels.

- DarkestHourDev/Maps/DH-Salaca_River_Clash.rom
Added radioman for axis;
increased # of arty calls:
allies 7->12
axis 5->10
slightly reduced minefield volume at f62
> salaca-river-clash-qol

- DarkestHourDev/Maps/DH-Winter_Stalemate_Advance.rom
Added:
-precap minefield protection for both sides;
-transport vehicles for both sides (opel/zis);
-collision for low poly static trees at map borders;
-15 min timer per cap;
-additional main spawn for both sides;
-radioman for axis and static radio for allies;
-few SM's (trench, sandbags, dead vehicles, trees)
-plus 2 arty calls for axis and changed delay; //6->6 allies 6->8 axis;
-noise/smooth pass on terrain, more snowdrifts and shell craters.
> Winter_Stalemate_Advance

- DarkestHourDev/Maps/DH-Riga_Docks_Push.rom
-updated all DHMineVolume with much cooler DHSpawnProtectMineVolume and correct their sizes;
-adjusted reinf intervals;
-moved setup boundaries;
-misc fixes.
> Riga_docks_push adjustments

- DarkestHourDev/Maps/DH-Oosterbeek_Advance.rom
-removed all rain ambient;
-fixed objective behavior - caps disabled after capture;
-axis group objective minefield expanded - it is big horizontal line;
-axis objective minefield sligtly adjusted;
-axis arty BAT 4_6 ArtilleryStrikeLimit=21,ArtillerySalvoAmount=SALVO_2_to_3,ArtilleryStrikeInterval=INT_Long_1m;
-allies BAT and SALVO 4_6 ArtilleryStrikeLimit=12,ArtilleryStrikeInterval=INT_VLong_3m;
-vehicles:
CromwellTank resp time 80->120, max active 2->1
ChurchillMkVIITank resp time 220->240
Cromwell95mmTank resp time 280->240
Tiger2BTank resp time 1100->210 max spawns 3->4
Stug3GDestroyer_Late resp time 70->120 max active 1->2
BrenCarrierTransport resp time 240->150 max active 2->1
JagdpantherTank_CamoTwo resp time 800->240 max spawns 255->4
Sdkfz251Transport_CamoThree resp time 220->120 …
> DH-Oosterbeek_Advance fixes and polishing.

- DH_GerPlayers/Classes/DHGEAntiTankRoles.uc
- DH_GerPlayers/Classes/DHGEEngineerRoles.uc
- DH_GerPlayers/Classes/DHGERadioOperatorRoles.uc
- DH_SovietPlayers/Classes/DHSOVAntiTankRoles.uc
- DH_SovietPlayers/Classes/DHSOVAssaultRoles.uc
- DH_SovietPlayers/Classes/DHSOVCorporalRoles.uc
- DH_SovietPlayers/Classes/DHSOVEngineerRoles.uc
- DH_SovietPlayers/Classes/DHSOVRiflemanRoles.uc
- DH_SovietPlayers/Classes/DHSOVSergeantRoles.uc
- DH_USPlayers/Classes/DHUSAntiTankRoles.uc
- DH_USPlayers/Classes/DHUSCorporalRoles.uc
- DH_USPlayers/Classes/DHUSEngineerRoles.uc
- DH_USPlayers/Classes/DHUSRadioOperatorRoles.uc
-DHUSRadioOperatorRoles carbine/grease/springfield -> garand
-DHUSAntiTankRoles carbine/grease -> garand
-DHUSEngineerRoles carbine/springfield -> carbine/springfield/garand
-DHUSCorporalRoles thompson/thompson20/garand -> thompson/grease/garand
-DHSOVRiflemanRoles m38/m91 -> m91
-DHSOVEngineerRoles m38 -> m38/m91
-DHSOVCorporalRoles svt40 -> svt40/m91
-DHSOVSergeantRoles ppd40/svt40/svt38 -> svt38/m91
-DHSOVAssaultRoles ppsh41 -> ppsh41/ppd40
-DHSOVAntiTankRoles Nagant1895 -> Nagant1895/TT -satchel
-DHGERadioOperatorRoles k98 -> k98/k98no cover +stiel granate
-DHGEEngineerRoles k98 -> k98/k98no cover -GLWeapon
-DHGEAntiTankRoles -GLWeapon
> US/SOV/GER roles overhaul.

- DH_Vehicles/Classes/DH_PanzerIVHTank_21stPanzerDiv_Normandy.uc
- DarkestHourDev/Maps/DH-Cambes-En-Plaine_Advance.rom
- DarkestHourDev/Textures/DH_VehiclesGE_tex.utx
New Map Variant:
- Cambes en Plaine converted to Advance game mode.
New PZIV Skin Used on Map:
- 21st PzD Normandy
> Cambes Advance Conversion

- DH_Weapons/Classes/DH_Winchester1897Bullet.uc
- DH_Weapons/Classes/DH_Winchester1897Fire.uc
Decreased spread and slightly increased ballistic coefficient and pellet damage.
> Trenchgun Tweaks

- DH_Engine/Classes/DHObstacleInfo.uc
- DH_LevelActors/Classes/DH_LevelActors.uc
This will allow sdk users to have more readability for dh placeable classes(ie draw scale).
> Enabled Display property for DH_LevelActors.

- DarkestHourDev/Maps/DH-MyshkovaRiver_Advance.rom
Collection of fixes for reported bugs in dhdev disco.
> Myshkova River fixes

- DarkestHourDev/Maps/DH-Rakowice_Advance.rom
Collection of tweaks and improvments for Rakowice Advance.
> Rakowice Advance update.

- DH_GerPlayers/Classes/DH_OstTruppenRifleman.uc
Fixed OstTruppenRifleman role incorrectly using Soviet sleeves.
> OstTruppen Sleeve Fix

- DarkestHourDev/Maps/DH-Lutremange_Domination.rom
Return of classic version of Lutremange using Domination game mode and updated with modern DH spawning and gameplay actors.
> Classic Lutremange

- DarkestHourDev/Maps/DH-MyshkovaRiver_Advance.rom
Collection of fixes and improvments for Myshkova River.
> Myshkova River Advance Update.

- DarkestHourDev/Maps/DH-Rakowice_Advance.rom
Collection of fixes and improvements for Rakowice Advance.
> Rakowice Advance Fixes.

- DH_Engine/Classes/DHWeaponAttachment.uc
- Override non-existent anims inherited from ROWeaponAttachment to resolve server log spamming.
> Updated Default Properties of DHWeaponAttachment

- DarkestHourDev/Maps/DH-Dzerzhinsky_Tractor_Factory_Advance.rom
- DarkestHourDev/Maps/DH-Grain_Elevator_Advance.rom
Ports of two Stalingrad-themed RO maps by me and Mad Death Hound.
- DH-Grain_Elevator_Advance 
- DH_Dzerzhinsky_Tractor_Factory_Advance
> Stalingrad Event Maps

- DarkestHourDev/Maps/DH-Lutremange_Domination.rom
As suggested, tankers now have a carbine
> Fixed tanker roles to have the m1a1 carbine

- DarkestHourDev/Maps/DH-Stavelot_Push.rom
-stavelot combat engineer didnt have a satchel, satchel added back
> Stavelot combat engineer fix

- DH_Vehicles/Classes/DH_SdKfz251_22Transport.uc
The change is made to make it lockable and consistent with Stummel.
> Made Pakwagen require a tank role

- DH_Weapons/Classes/DH_G41Fire.uc
- DH_Weapons/Classes/DH_G43Fire.uc
- DH_Weapons/Classes/DH_M1A1CarbineFire.uc
- DH_Weapons/Classes/DH_M1CarbineFire.uc
- DH_Weapons/Classes/DH_M1GarandFire.uc
- DH_Weapons/Classes/DH_SVT38Fire.uc
- DH_Weapons/Classes/DH_SVT40Fire.uc
- DarkestHourDev/Animations/DH_Garand_1st.ukx
- all semi auto rifles now have recoil curves, similar to the ones on full-auto rifles
- changed garand recoil curve to be less impacting, changed garand recoil animation to have sight obstruction
> Recoil curves on self loading rifles

- DH_Vehicles/Classes/DH_50CalVehicleBullet.uc
- DH_Vehicles/Classes/DH_BesaVehicleBullet.uc
- DH_Weapons/Classes/DH_30calBullet.uc
- DH_Weapons/Classes/DH_AVT40Bullet.uc
- DH_Weapons/Classes/DH_BARBullet.uc
- DH_Weapons/Classes/DH_BARNoBipodBullet.uc
- DH_Weapons/Classes/DH_DP27Bullet.uc
- DH_Weapons/Classes/DH_DP27LateBullet.uc
- DH_Weapons/Classes/DH_DP27LateWeapon.uc
- DH_Weapons/Classes/DH_FG42Bullet.uc
- DH_Weapons/Classes/DH_G41Bullet.uc
- DH_Weapons/Classes/DH_G43Bullet.uc
- DH_Weapons/Classes/DH_G43ScopedBullet.uc
- DH_Weapons/Classes/DH_Kar98Bullet.uc
- DH_Weapons/Classes/DH_Kar98ScopedBullet.uc
- DH_Weapons/Classes/DH_M1GarandBullet.uc
- DH_Weapons/Classes/DH_MG34Bullet.uc
- DH_Weapons/Classes/DH_MG42Bullet.uc
- DH_Weapons/Classes/DH_MN9130Bullet.uc
- DH_Weapons/Classes/DH_MN9130ScopedBullet.uc
- DH_Weapons/Classes/DH_MN9130ScopedPEBullet.uc
- DH_Weapons/Classes/DH_PTRDBullet.uc
- DH_Weapons/Classes/DH_SVT38Bullet.uc
- DH_Weapons/Classes/DH_SVT40Bullet.uc
- DH_Weapons/Classes/DH_SVT40ScopedBullet.uc
- DH_Weapons/Classes/DH_SpringfieldA1Bullet.uc
- DH_Weapons/Classes/DH_SpringfieldScopedBullet.uc
- DH_Weapons/Classes/DH_ZB30Bullet.uc
- increased flesh damage for .50 and PTRD significantly
- minor adjustment of rifle caliber damage
- fixed DP27 name
> Bullet damage adjustment

- DH_Engine/Classes/DHPawn.uc
- DH_Engine/Classes/DHPlayer.uc
- DH_Engine/Classes/DHVehicleRegistry.uc
Vehicle registry complete, all vehicles abbreviated with names and variants. ready for merge
> Feature registry vehicles

- DH_Weapons/Classes/DH_30calFire.uc
- DH_Weapons/Classes/DH_MG42Fire.uc
-Increased mg42 hip-fire recoil to 1.5
-Reduced m1919 hip-fire recoil to 1.5
added for consistency
> Changed the hipfire recoil between the mg42 and m1919a6 to better reflect consistency 

- DarkestHourDev/Maps/DH-Facing_Worlds_Clash.rom
> Darkest Hour: Space

- DarkestHourDev/Maps/DH-Endsieg_Advance.rom
New event map: Endsieg Advance.
> Endsieg Advance

- DH_Weapons/Classes/DH_F1GrenadeAmmo.uc
- DH_Weapons/Classes/DH_M1GrenadeAmmo.uc
- DH_Weapons/Classes/DH_MillsBombAmmo.uc
- DH_Weapons/Classes/DH_StielGranateAmmo.uc
Like it says on the tin, restored most grenades to their original initial ammo value of 2.
> Increased initial ammo for most standard issue grenades to 2.

- DH_Equipment/Classes/DHShovelBuildFireMode.uc
Simple change, but so nice for all logi players.
Nothing more than that, really.
> Set Shovel BuildFireMode to automatic

- DH_Construction/Classes/DHConstruction_VehiclePool.uc
- DH_Construction/Classes/DHSpawnPoint_VehiclePool.uc
- DH_Engine/Classes/DHPlatoonVPMessage.uc
- DH_Engine/Classes/DHVehiclePoolMessage.uc
Vehicle pools are really important to the team, but they're not broadcast when constructed.
As a logi player I'd like this to be broadcast so I don't have to spend time on telling the team this.
> Added a broadcasted message when a vehicle pool is activated.

- DarkestHourDev/Maps/DH-Jurques_Dusk_Advance.rom
> Jurques Dusk:

- DH_USPlayers/Classes/DH_AmericanPawn.uc
- DH_USPlayers/Classes/DH_AmericanPawnNCO.uc
- DH_USPlayers/Classes/DH_USVest7thPawn.uc
- DH_USPlayers/Classes/DH_USVestPawn.uc
- Resolved an issue with USVestPawn and USVest7thPawn that resulted in incorrect skins being used for these pawns.
- Fixed some spacing issues in DH_AmericanPawn and DH_AmericanPawnNCO.
> Bugfix US Pawns

- DH_Construction/Classes/DHConstruction_Resupply.uc
- DH_Construction/Classes/DHConstruction_Resupply_Vehicles.uc
- Reduced infantry resupply ticks from 100 to 30.
- Reduced vehicle resupply ticks from 100 to 15.
> Rebalanced Ammo Crate Constructions

- DH_Engine/Classes/DHPlayer.uc
- DH_Interface/Classes/DHCommunicationPage.uc
- DH_Interface/Classes/DHMidGameVoiceChat.uc
The muting functionality was there but it wasn't utilized.
Also renamed it from "Ignore Speech" to "Ignore Voice Commands".
> Fixed "Ignore Voice Commands" feature not working

- DarkestHourDev/Maps/DH-Endsieg_Advance.rom
- Fixed loading time issue with new minefields.
> Endsieg Advance:

- DarkestHourDev/Maps/DH-Armored_Yaryshivka_Domination.rom
- DarkestHourDev/Maps/DH-Reichswald_Advance.rom
Armored Yaryshivka:
- Fixed infinite respawning AT guns.
- Fixed tanks were unable to capture objectives.
- Fixed all tanks were marked as spawn vehicles.
- Reduced round timer to 60 minutes from 80.
Reichswald:
- Fixed missing Allied main supply cache.
> Hotfix for New Maps

- DarkestHourDev/Animations/DH_Halloween_anm.ukx
- DarkestHourDev/Maps/DH-Haunted_Flugplatz_Survival.rom
- DarkestHourDev/Maps/DH-Haunted_Pariserplatz_Survival.rom
-Removed rifles and nade class from zombies
-Removed extra weapons from Zleader
-Fixe issues on Flugplatz that werent properly saved earlier
> Removed some of my earlier changes that made zombies too OP

- DarkestHourDev/Maps/DH-Haunted_Flugplatz_Survival.rom
- DarkestHourDev/Maps/DH-Haunted_Inferno_Verde_Survival.rom
- DarkestHourDev/Maps/DH-Haunted_Pariserplatz_Survival.rom
- Added several new areas.
- Restricted Allies from going outside of the manor itself and the courtyard (no more hiding in bushes).
- Added a scripted console command that sets Allied Reinforcements to 0 at the end of setup phase, to prevent scenarios where the game does not end correctly.
> Update to Inferno Verde by SoulSeek:
