DH_Engine/Classes/DHGameReplicationInfo.uc
DH_Engine/Classes/DHHud.uc
DH_Engine/Classes/DHPlayer.uc
DH_Engine/Classes/DHSquadReplicationInfo.uc
DH_Engine/Classes/DHVehicle.uc
DH_Engine/Classes/DHVoiceChatRoom.uc
DH_Engine/Classes/DHVoiceReplicationInfo.uc
DH_Engine/Classes/DarkestHourGame.uc
DH_Interface/Classes/DHTab_Controls.uc

* Removed limit on VoiceID to be less than 32 (will break bit field masks, so muting players, local, and public channels will no longer work)
* Replaced "Team" channel with "Unassigned"
* Replaced "Public" channel with "Command"
* Hijacked "Local" channel so it is no longer used and instead when a player "Speaks Local" they speak in their own private voice channel
* Changed the IsMember() function to handle new channels appropriately
* Change some default controls to fit the changes
Note how it all works:
The "Team" channel is now just labeled as "Unassigned" and it basically acts the same way as it did before, but now it will ignore players that are in a squad.  Also I've made it so if you are in a squad, you can't "Speak Unassigned" which if allowed would be confusing (speak but not …

Significant changes to the voice system!

---

DH_Engine/Classes/DHGameReplicationInfo.uc

Tested on rotated maps along with non-rotated maps.
Markers now match up to where you place them.

Fix for bug https://github.com/DarklightGames/DarkestHour/issues/911

---

DH_Construction/Classes/DHConstruction_Resupply.uc
DH_Construction/Classes/DHConstruction_Resupply_Vehicles.uc
DH_Engine/Classes/DHGameReplicationInfo.uc
DH_Engine/Classes/DHHud.uc
DH_Engine/Classes/DHResupplyAttachment.uc
DarkestHourDev/Textures/DH_InterfaceArt2_tex.utx

Initial Changes:
* Added 2 icons for Infantry and Vehicle munition boxes
* Reduced size of the supply cache icon
* Munition boxes (both infantry and vehicle) now show on the map for friendlies (via HUD changes)
* Added replicated array in GRI to keep track of the resupply attachments for client use to display them on the map
* ResupplyAttachment is now a dumb_proxy replicated actor (required so client knows location and other replicated variables)
* Added replicated variable to ResupplyAttachment to determine if it should draw on the map or not (this way its not drawn for logi-trucks, etc.)
Notes:
Tested to work in MP, more testing is needed with enemies and digging them up. Icons use the same color as the team color but its defined in the widgit to save on function calls.

Initial commit for Munition Changes

---

DH_Engine/Classes/DHPawn.uc
DH_Engine/Classes/DHThrowableExplosiveDamageType.uc

Hi,
I found that there is this existing DamageType.uc property "bThrowRagdoll" and it probably may help resolve TODO note from DHPawn line 2129:
> // TODO: add others explosive types & try to remove projectile-specific literals as far as possible
As far as I can tell both ROMineDamType and ROSMineDamType have bThrowRagdoll set to false so they cannot be removed from this if() statement completely (being outside of scope for this repository).
DHATMineDamage was fine to remove as it extends ROTankShellExplosionDamage with bThrowRagdoll==true.
All three DH_* classes inherit from DHThrowableExplosiveDamageType.uc for which value is changed in this pr.

Existing bThrowRagdoll may be a candidate to replace hardcoded class literals

---

DH_Interface/Classes/DHDeployMenu.uc

Displaying proper information that a squad cannot be locked if it is too small (i.e. it has less than 3 members).

#1070 adding new 'can't lock squad' tooltip

---

DarkestHourDev/Maps/DH-Hurtgenwald_Advance.rom

- Potential fix for Ruins and Pak Bunker objective capture issue.
- Increased reinforcements value for Allies to 21 (was 19) and Axis to 20 (was 17).
- Slightly expanded minefield volume protecting Axis main spawn.

Bugfixes for Hurtgenwald Advance

---

DarkestHourDev/Maps/DH-Carpiquet_Airfield_Advance.rom
DarkestHourDev/Maps/DH-Rakowice_Advance.rom

Significantly overhauled Carpiquet Airfield level:
- Optimization pass with improved culling for various statics and grass. Removed decolayer grass underneath wheat fields. Reduced overall resource usage in heaviest parts of the map.
- Bug fixes for various floating objects, spawnhints facing the wrong direction, transparent walls in small hangars and removed the ability to build AT guns on roofs.
- Replaced HQs with objective spawns.
- Rebalanced roles and constructions for both teams to better reflect historical situation. 
- Added limited Panther G tanks to Axis, added limited Sherman Firefly tanks to Allies.
- Increased view distance by roughly 50-75 meters. 
- Changed lighting and removed haze.
- Removed ticket bleed from all but first objective, set Refueling Area objective to …

Carpiquet Overhaul and Rakowice Advance

---

DarkestHourDev/Maps/DH-WIP_Prussia_Push.rom

* Renamed Bunker objective to Dugout
* Fixed the "death on spawn" issue on the Dugout obective
* Moved Dugout spawn point back to the street
Author: Pvt.Winter

Fixes for Prussia Push

---

DarkestHourDev/Maps/DH-Rakowice_Advance.rom

Rakowice Advance: 
- Changed minefield timers as per issue #1171 (was 6 seconds, now 10). 
- Increased lockdown timer on middle 3 grouped objectives when captured by Allies to 7 minutes (was 3.5). 
- Added T-60 light tank spawn to Allies. 
- Made Universal Carrier spawns unlimited, but increased respawn timer.

Rakowice Advance

---

DH_Vehicles/Classes/DH_Stug3GDestroyer.uc

adjusted stug armor angle values to remove/reduce amount of glitchy deflections when frontal armor is somehow counted as "side", it seems to work although these deflections still sometimes happen

stug armor fix

---

DH_GerPlayers/Classes/DH_GermanArdennesFJPawn.uc
DarkestHourDev/Textures/DHGermanCharactersTex.utx

Renamed FJ_tan&water camo to FJ_TanAndWater in DHGermanCharactersTex package and DH_GermanArdennesFJPawn. The ampersand symbol in the previous name appeared to prevent this specific camo from ever spawning as intended.

FJ45 Pawn Fix

---

DarkestHourDev/Maps/DH-Konigsplatz_Push.rom
DarkestHourDev/Maps/DH-WIP_FallenHeroes_Clash.rom

DH-Fallen_Heroes_Clash, DH-Konigsplatz_Push
- adjusting tank respawn times
- making KT and PZIV spawnable on Konigsplatz

Level updates

---

DH_Guns/Classes/DH_45mmM1937GunCannonShell.uc
DH_Guns/Classes/DH_45mmM1942GunCannonShell.uc
DH_Vehicles/Classes/DH_AchillesCannonShell.uc
DH_Vehicles/Classes/DH_BT7CannonShell.uc
DH_Vehicles/Classes/DH_BT7Tank.uc
DH_Vehicles/Classes/DH_ShermanFireFlyCannonShell.uc
DH_Vehicles/Classes/DH_StuartCannonShell.uc
DH_Vehicles/Classes/DH_StuartTank.uc
DH_Vehicles/Classes/DH_T60Tank.uc
DH_Vehicles/Classes/DH_TigerCannon.uc

- fixed tiger 1 turret front armor to a more accureate value (125, used to be 171 which is completely wrong, IRL it varied between 100 and 150)
- fixed inconsistency between identical shells (firefly)
- reduced health for T-60, BT-7 and stuart tanks as they were too survivable for small and light tanks
- slightly buffed damage for 37mm and 45mm shells

Tank fixes1

---

DarkestHourDev/Maps/DH-Pariserplatz_Defence.rom
DarkestHourDev/Maps/DH-Putot-en-Bessin_Advance.rom
DarkestHourDev/Maps/DH-Varaville_Advance.rom

Pariserplatz: 
- Converted to the "Defence" game mode. 
- Added several entirely new interiors, offices, lobbies and misc. rooms to expand the map.
- Connected various existing rooms to enable players to traverse parts of the map through buildings instead of the street.
- Updated several existing interiors to be more unique.
- Rebalanced tank loadouts to be more historically accurate, as well as closer to the classic RO version of the map.
- Reworked the pre-placed AT guns to use the randomizer system. 
- Added a new trenchline in the Park area. 
- Added various new details around the map.
- Fixed various misc. bugs. 
- All of the additions above should still be considered Work in Progress, but is functional.
Varaville:
- Fixed several bugs with objective reliances resulting in unintended …

Pariserplatz Defence and various bug fixes/balance changes.

---

DarkestHourDev/Maps/DH-Cholm_Advance.rom
DarkestHourDev/Maps/DH-Rabenheck_Advance.rom

Cholm
Added debre and rubble to the streets and small stones as decolayers
Improved perfromance by adding Cull distastance to SM
Rabenheck
Removed the Swamp Obj
Blocked off bushes near end of the map to remove"high-speed highway"
~~Rhine River~~
~~Various changes to the map to make it brighter and easier to spot the enemy~~
~~Changed Obj names to more realistic names instead of names of Devs~~
~~Improved general performance on the map and fixed FPS issue in the "Bassnett Farm area"~~

Mapchanges 11/4

---

DarkestHourDev/Maps/DH-Berezina_Advance.rom
DarkestHourDev/Maps/DH-Pegasus_Bridge_Advance.rom

Pegasus Bridge Advance: 
- Kashash unloaded myLevel package.
- Experimental Axis spawn changes to simulate a "surprise" attack on the Bridge. 
- Moved Allied spawns forward, added some new spawns and moved main spawn protection minefield forward slightly. 
- Rebalanced reinforcement interval progression and overall reinforcement amount. 
- Slightly increased capture speeds for the Bridge and Cafe objectives. 
- Reworked DZ to be slightly more forgiving to the Allies. 
- Reduced Axis logi significantly (last attempt before removal)
- Removed Axis mortar operator and observer roles. 
- Removed Allied paradrop.
- Reduced DramaticLightingScale.
- Fixed resupply volumes being of the incorrect type. 
- Fixed a BSP bug and some strange collisions in the Town Hall.
- Fixed water killing you too …

Balance Changes and Bug Fixes for Pegasus Bridge and Berezina

---

DH_Construction/Classes/DHCommandMenu_ConstructionGroup.uc
DH_Construction/Classes/DH_ConstructionWeapon.uc
DH_Engine/Classes/DHConstruction.uc
DH_Engine/Classes/DHConstructionErrorMessage.uc
DH_Engine/Classes/DHConstructionManager.uc
DH_Engine/Classes/DHGameReplicationInfo.uc
DH_Engine/Classes/DH_LevelInfo.uc
DH_Engine/Classes/DarkestHourGame.uc

This branch implements the ability for levelers to determine a maximum # of certain types of constructions to be built over the duration of a round. This is meant to be used specifically for AT guns to reduce the incidence of AT gun spam.

Level designers can now limit the number of constructions available per round

---

DarkestHourDev/StaticMeshes/DH_Buildings.usx

- Fixed collision mesh for "Sepp Window" static that was causing server log spam.

"Sepp Window" Static Collision

---

DH_Vehicles/Classes/DH_BT7CannonPawn.uc
DH_Vehicles/Classes/DH_BT7Tank.uc

BT7:
- Added missing periscope to the BT-7 gunner's position (currently uses the same periscope overlay as the T-34, both of which need to be replaced in the future).
- Fixed broken ammo hit points on the BT-7.

BT-7 Periscope

---

DarkestHourDev/Maps/DH-Armored_KrivoiRog_Clash.rom
DarkestHourDev/Maps/DH-Dead_Man's_Corner_Push.rom
DarkestHourDev/Maps/DH-GunAssault_Push.rom
DarkestHourDev/Maps/DH-Hedgerow_Hell_Advance.rom
DarkestHourDev/Maps/DH-Kommerscheidt_Advance.rom
DarkestHourDev/Maps/DH-Pariserplatz_Defence.rom
DarkestHourDev/Maps/DH-St_Marie_du_Mont_Advance.rom
DarkestHourDev/Maps/DH-Stoumont_Advance.rom
DarkestHourDev/Maps/DH-Winter_Stalemate_Clash.rom

St. Marie du Mont:
- Reduced Allied respawn interval for the first objective slightly.
- Put a limit on Sherman tanks for the Allies, now 12 max spawns.
- Added 2 new flanking routes for Allies to enter the town itself. 
- Implemented AT gun limits.
Gun Assault:
- Added a starting "gimme" objective to give Axis some time to defend the bridge.
- Reworked spawn points slightly to hopefully improve the flow of the map.
- Gave Axis a single PZIIIN as per the old version of this map. 
Dead Man's Corner:
- Removed Gebalte Ladung from Axis tank hunter class.
- Added blocking volumes to various hedges around the map to prevent people from climbing on top and laying in the shrubbery.
- Reduced Allied reinforcement interval. 
- Moved some Allied spawns to hopefully give more cover.
Armored Krivoi …

Bug Fixes and Balance Changes to Various Levels

---

DarkestHourDev/Maps/DH-Kriegstadt_Advance.rom

Kriegstadt Advance:
- Removed bad reference to EH-BerlinTanksMod4 in a blocking volume. 
- Fixed broken Axis objective spawnhints on the Bank objective.

Kriegstadt Hotfix

---

DH_Vehicles/Classes/DH_TigerCannon.uc

tiger's turret front armor was varying between 100-150 mm; current value of 171 is completely wrong. It should be changed to at least somewhere in the range of 100-150

set tiger front turret armor to a more accurate value

---

DH_Engine/Classes/DHPlayer.uc
DH_Engine/Classes/DHSpawnPointBase.uc
DH_Engine/Classes/DHSpawnPoint_SquadRallyPoint.uc

Squad leaders now spawn instantly on rally points if they have one spawn remaining. The squad must have more than one member for this behavior to work.
This was done to eliminate the behavior where players would hold spawn until the squad leader could use the rally point (usually failing to do so and the whole squad being disappointed in one another).

Squad leaders now spawn instantly on rally points if they have one spawn remaining

---

DarkestHourDev/Maps/DH-Haunted_Pariserplatz_Survival.rom

-Reduced cap times of first 4 caps
-Increased resupply volumes sizes so it
-Changed team ratios to 60 40 (more allies)
-Removed 1 SMG from allied team for low player numbers
-Added way more pickups in caps
-Slightly adjusted zombie spawn locations

Balancing on Haunted Pariser

---

DH_Vehicles/Classes/DH_M3Halftrack.uc
DH_Vehicles/Classes/DH_SdKfz2519DTransport.uc
DH_Vehicles/Classes/DH_Sdkfz251Transport.uc

A few hotfixes for half-tracks and half-track based vehicles

---

DarkestHourDev/Maps/DH-Dom-Pavlova_Event.rom

Event version of Dom Pavlova with objectives removed, DZ disabled, minefields altered, roles changed, a few new interiors/small tweaks to existing ones and pre-placed HQs added (these will be fortified during the round and used as bases for the team commanders/targets).

Event Version of Dom Pavlova

---

DarkestHourDev/Maps/DH-La_Fiere_Day_Advance.rom

The lines were set to be tight and close to the objectives to prevent
both teams from aggressive flanking, especially in the first half
of the map.
This should also give Allies (albeit minor) protection for reinforcing
the Church area, as their only safe access to it is through the narrow
causeway.
* Enabled `bMainSpawn` on all main spawns.
* Set Danger Zone influences to:
```
[0:La Fière]
AxisInfluenceMoifier=0.00
NeutralInfluenceMoifier=0.20
[1:Estate Farm]
AxisInfluenceMoifier=5.00
NeutralInfluenceMoifier=0.10
[2:Church]
AxisInfluenceMoifier=6.00
NeutralInfluenceMoifier=0.50
[3:Causeway]
AlliesInfluenceMoifier=2.00
[4:Barn]
[5:La Fière Manor]
AxisInfluenceMoifier=4.00
[6:Exit]
AlliesInfluenceMoifier=5.00
NeutralInfluenceMoifier=0.10
```

[La Fiere Day Advance] Hand-tuned the Danger Zone

---

DH_Engine/Classes/DHRocketFire.uc

The bug can be reproduced by firing a rocket launcher shortly after
stopping into a standstill with a high enough ping.
Since it's tricky to reproduce on a local server, this was tested by
forcing `AllowFire()` to always fail on a server, which gives similar results.

Fixed a bug where AT launchers could fail to spawn a projectile

---

DarkestHourDev/Maps/DH-Les_Champs_de_Losque_Advance.rom

Les Champs de Losque:
- Fixed various issues with spawn hints on the map.
- Fixed an issue with a fluid surface that was poking out of the terrain.
- Fixed a missing artillery trigger on a static radio.
- Replaced the Wirblewind static with a Panzer IVH.

Les Champs de Losque Hotfix

---

DH_Engine/Classes/DHGameReplicationInfo.uc
DH_Engine/Classes/DHPlayer.uc
DH_Engine/Classes/DHScoreManager.uc
DH_Engine/Classes/DarkestHourGame.uc
DH_Interface/Classes/DHScoreBoard.uc

This PR adds the display of a team's score totals (kills, deaths, combat score/support etc.) on the scoreboard at the end of a round.
To achieve this, I assigned each team its own `DHScoreManager`. When a player joins a team, their own `DHScoreManager` is linked to their respective team's (via a `NextScoreManager` variable, effectively a linked list), and all evaluated scoring events are passed through to the team's. Team scoring managers ignore any sort of rate-limiters for scoring events that apply to individual players. In theory, this type of chaining would allow us to do the same thing for tracking squad scores as well, if we want to go down that route later.
Note that the scores above will appear strange because I got a bunch of kills against bots on both teams.
Additional changes: …

Team score totals are now displayed at the end of the round

---

DarkestHourDev/Maps/DH-Kriegstadt_Advance.rom

- moved axis vehicle spawn to the end of the central street and restricted all vehicles from entering that abusive camping spot behind p4 wreck, where german tank cannot be seen from the other side at all due to fog range and being covered by a building.
- in order to prevent continuous meatgrinders at the beginning of the map (between kaschade and the first street, where the space to move around is scarce), axis respawn time is increased by 10 seconds for the first 2 objectives
- made the first objective faster capping
- restricted axis from entering the first street in prep phase
- reduced allied reinforcements by 2 points, axis by 1
- removed team ratio difference (axis were at disadvantage)
- increased axis bleed in the end in 2 times
- upped german WH rifleman limit from 8 to 13
- …

Kriegstadt improvements

---

DarkestHourDev/Maps/DH-Armored_Fruhlingserwachen_Clash.rom
DarkestHourDev/Maps/DH-Armored_Suedwind_Advance.rom
DarkestHourDev/Maps/DH-Bridgehead_Advance.rom
DarkestHourDev/Maps/DH-Reichswald_Advance.rom

Bridgehead Advance:
- Generally reverted the map to its previous state.
- Removed pre-placed HQs for the Axis.
- Added Objective Spawns instead for both teams.
- Implemented AT gun restrictions.
- Added radios to the map.
- Implemented new anti-precap and spawn protection minefields for both teams.
- Rebalanced roles slightly.
- Rebalanced vehicle loadouts slightly.
Reichswald Advance:
- Implemented AT Gun Limits.
- Increased Allied tank availability.
- Rebalanced roles slightly.
Armored Fruhlingserwachen Clash:
- Changed game mode to Domination (victory will now be determined by who controls the most objectives).
- Fixed a bug where the Farm Lutzow objective had some incorrect properties set.
Armored Suedwind Advance:
- Significantly increased Allied ticket count to hopefully resolve the …

Tweaks for the Operation Veritable Event

---

DarkestHourDev/Maps/DH-Winter_Manor_1941_Push.rom

- improved manor exterior
- added terrain decolayers
- removed ba64
- removed g41
- fixed bt7 activating
- fixed soviet engineer
Author: kashash

Fixes for Winter Manor Push

---

DH_Vehicles/Classes/DH_GMCTruck.uc

This reverts changes made to the steering curve done in ac8e8cbed0f1cecd439021ae8c4f5edba57d6a09, which made GMC significantly more maneuverable compared to the other trucks in the game

Increased GMC understeer to be consistent with other trucks

---

DarkestHourDev/Maps/DH-St_Marie_du_Mont_Advance.rom

Slightly reduced deco density;
added grenade to axis radioman kit;
changed number of artillery calls:
axis 3->9 and quality nerf(less salvo, higher delay);
allies 3->15

st-marie-du-mont-advance-qol

---

DarkestHourDev/Maps/DH-Winter_Stalemate_Advance.rom

-fixed emitter render on normal/low world detail settngs;
-added cover for allies at last cap;
-increased center cap requirement 4->6 players;
-moved setup phase black box closer to cap for allies;
-removed supply cache from allowed buildings;
-moved endgame camera.

winter_stalemate_advance-qol

---

DarkestHourDev/Maps/DH-St_Marie_du_Mont_Advance.rom

-fixed reported floaters;
-both teams +1 at role count;
-axis sl and at role gain access to k98; //had only mp40
-removed gl from axis ce;
-removed colt handgun from allies rifleman role; //ALL other roles still had it
-added 2 riflemans with springfield bolt action; //since usuall role kits ce/at don't have it as choise
-added 2 active m3a1 on 90s cd;
-added 1 active sdkfz251 transport on 90s cd;
-added 1 active opel transport 60s cd;
-arty redone(or restored) from axis/allies 3 calls BAT_15 SALVO 2_3 30s CD to
allies: 19 calls BAT 8_2 SALVO 2_3 CD 1min Normal Pattern
axis: 13 calls BAT 8_2 SALVO 2_3 CD 3min Loose Pattern. //salvo 2_3 is really pain free

SMDM tiny fixes and adjustments.

---

DH_Engine/Classes/DHThrowableExplosiveProjectile.uc
DH_Weapons/Classes/DH_SatchelCharge10lb10sProjectile.uc

It was introduced in 7dd0ffd413939c0aa24ab8962de14202fdc24456.
- Air-bursting grenades on purpose does not impair the overall feel
of the game or its "authenticity".
- This logic only works if players know about it, which they most
assuredly don't. Unless they were unfortunate enough to read about it
in the patch notes half a decade ago.

Removed code that reduces damage for air-bursting explosives

---

DarkestHourDev/Maps/DH-MyshkovaRiver_Advance.rom

-removed all APs;
-removed first two caps;
-removed vehicle pool from constructions;
-myshkova intersection and bridgehead now one big cap;
-caps no longer can be recaptured;
-added objective spawns(inf and veh), precap minefields;
-revised roles, vehicles, arty and activation logic;
-updated reinforcement interval been fixed and triggers;
-updated lightning;
-static radios are functional;
-replaced low poly woods;
-added some terrain variety;
-replaced static zis3 and pak40 with enterable ones;
-added radioman for axis;
-updated minefild/block/objective/spawn protection volumes.

Myshkova_River-Overhaul

---

DarkestHourDev/Maps/DH-La_Fiere_Advance.rom

-added advancing minefields for both teams;
-fixed spawns at Causeway obj; //axis used allies hints and vice verca
-allies rifleman -handgun;
-allies sergeant thompson -> m1a1;
-axis mg count 3->2;
-axis SL role +kar98.

La_Fiere_Advance advancing minefields

---

DH_Engine/Classes/DHGameType_Armored_Advance.uc
DarkestHourDev/Maps/DH-Armored_Freyneux_Advance.rom

New Game Mode:
- Armored Advance, uses time instead of tickets to help with balancing tank maps.
- Converted Armored Freyneux Advance to use this game mode.

Armored Advance Game Mode

---

DarkestHourDev/Maps/DH-Flakturm_Tiergarten_Defence.rom

Flakturm Tiergarten:
- Tanks besides Su76 and Pakwagen unlock after Allies capture University and Park objectives.
- Removed logi from both teams.
- Removed Hetzer.
- Reduced SMG roles on both teams.
- Fixed some small collision bugs.

Flakturm Update

---

DarkestHourDev/Maps/DH-Flakturm_Tiergarten_Defence.rom
DarkestHourDev/Maps/DH-Pariserplatz_Defence.rom

Pariser:
- Main supply cache restored with max 1000 supply.
- Supply cache construction disabled.
- 88s disabled.
- Howitzers disabled.
- Pak 40 limited to 1 max with 15 minute regen timer.
- Removed Axis Hetzer.
- Reduced Soviet artillery to 3 strikes.
- Removed German respawn timer penalty at last objective.

Pariser Update

---

DH_USPlayers/Classes/DH_USTankerPawn.uc
DH_USPlayers/Classes/DH_USWinterPawn.uc

- Fixed a bug where US Tanker and Winter Pawns were inheriting incorrect bodyskin textures from AmericanPawn.

Hotfix for US Winter and Tanker Pawns

---

DarkestHourDev/Maps/DH-Cambes-En-Plaine_Advance.rom
DarkestHourDev/Maps/DH-Smolensk_Advance.rom

Cambes en Plaine Advance:
- Reduced German tank count by 1 and increased PZIV Respawn timer to 2:30.
- Increased Allied Bren carrier spawns by 1.
- Reduced Allied artillery cooldown timer to 1 minute.
Smolensk Advance:
- Added spawn protection mine volumes for Allies.

Small Tweaks to Cambes and Smolensk:

---

DarkestHourDev/Maps/DH-German_Village_Advance.rom
DarkestHourDev/Maps/DH-Lazur_Chemical_Plant_Defence.rom
DarkestHourDev/Maps/DH-Lutremange_Domination.rom
DarkestHourDev/Maps/DH-Rhine_River_Clash.rom

Lutremange Domination:
- Added DZ to both main spawns to allow for vehicle spawning.
- Replaced Greyhound with Stuart and Easy 8 Sherman with M4A3 76w.
- Reduced intensity of artillery for both teams.
Lazur Chemical Plant:
- Fixed incorrect materials on myLevel package textures (used pretty heavily on the map, so many walls, windows, signs, etc., will now have correct impact FX)
- Expanded protection minefield for AlliedSpawn2A to prevent spawn killing (caused by addition of mantling in DH that allowed access to areas not possible in RO).
- Fixed bugged lighting in some areas.
- Increased tickets for both teams significantly.
- Fixed bugged satchel doors.
German Village Advance:
- Fixed issues with NoArty volumes blocking most of the map.
- Fixed exploit that could allow users to get …

New map hotfixes

---

DH_Engine/Classes/DarkestHourGame.uc

Has no noticeable effect on performance and ruins experience more than a badly performing server.

Removed performance scaling of respawn times

---

DH_Engine/Classes/DHMapDatabase.uc
DarkestHourDev/Maps/DH-Dzerzhinsky_Tractor_Factory_Advance.rom
DarkestHourDev/Maps/DH-Rabenheck_Advance.rom
DarkestHourDev/Maps/DH-Varaville_Advance.rom
DarkestHourDev/StaticMeshes/DH_Vegetation4_stc.usx

Dzerzhinsky:
- Opened an additional side route for Axis to advance on the first street.
- Added a breach in the wall near south commons.
- Increased Axis respawn timer to 10 seconds (was 5).
- Moved some of the Soviet objective spawn hints to have more cover.
- Replaced anachronistic AK47 posters on the map.
- Added some additional details and cover in a few areas.
- Fixed collision issues with tree branches.
- Increased cooldown timer on Allied artillery.
- Implemented gun limits.
- Removed floating cups outside of apartment building objective.
Rabenheck:
- Added some additional trenches and pillboxes around the map.
- Set all main spawns to have the main spawn flag = true and configured DZs.
- Adjusted Allied DZ influence on all objectives.
- Added minimum player capture requirements …

Level Updates and Fixes

---

DarkestHourDev/Maps/DH-Cambes-En-Plaine_Advance.rom

- Added new unlock progression to Axis tanks, Axis now start with 4 PZIV spawns and 1 Panther after the village is captured and unlock more as the map progresses.
- Allies start with only 3 Fireflies now, but unlock an additional 1 for every objective taken resulting in a net increase of 2 spawns, now more spread out to be available when needed. 
- Fixed an issue where Allied tankers lost their Vehicle Objective Spawn after taking the Cambes Woods objective.

Update to Cambes en Plaine Advance:

---

DH_Engine/Classes/DHConstruction.uc
DH_Engine/Classes/DHMapIconAttachment_Resupply.uc
DarkestHourDev/Textures/DH_InterfaceArt2_tex.utx

- Disabled placement of all constructions within the danger zone to curb spawn camping, blocking entrances, and other unfair play involving logistics deep behind the lines.
- Ammo crates are made visible to the enemy team when inside the danger zone.
- Replaced vehicle ammo icon (smaller to avoid visual clutter and more consistent with the infantry ammo icon).

Changes to constructions: danger zone placement and visibility

---

DH_Weapons/Classes/DH_MG42Fire.uc

-Hipfire penalty raised from 1 to 1.5
MG42 recoil was too controllable, raised from 1 to 1.5 to ensure people cannot "snipe" with a heavy machine-gun

MG42 hipfire recoil increase

---

DH_Engine/Classes/DHMapDatabase.uc
DarkestHourDev/Maps/DH-Champs_d'Agonie_Advance.rom
DarkestHourDev/Maps/DH-Kharkov_Advance.rom
DarkestHourDev/Maps/DH-Klin1941_Advance.rom
DarkestHourDev/Maps/DH-La_Fiere_Day_Advance.rom
DarkestHourDev/Maps/DH-Lyes_Krovy_Defence.rom
DarkestHourDev/Maps/DH-Ten_Aard_Advance.rom

Champs d'Agonie Advance:
- Added spawn protection minefields for Allies.
- Increased respawn timer for Panther and Jagdpanzer IV from 220 and 180 seconds to 300 and 220 respectively.
- Decreased respawn timer for M4A3 105mm and Sd.Kfz. 231/1 from 200 to 150 and 170 to 140 seconds.
- Reduced Allied respawn timer from 20 seconds to 15.
- Gave Allies a +1% team ratio advantage (more meant to prevent situations where Axis end up having more players, ideally they should stay around even with Allies having a small advantage).
Kharkov Advance:
- Fixed some BSP lighting bugs around the map.
- Fixed a few misc. floating objects.
- Fixed terrain holes.
- Increased Soviet tanks from 5 to 6.
- Reduced Axis ticket modifier significantly from 45 to 30.
Klin 1941 Advance:
- Fixed a bug where the German …

Misc. Fixes and Balance Changes to Various Maps

---

DarkestHourDev/Maps/DH-Barashka_Clash.rom

-german combat engineer was using the deprecated "small satchel" class
fixed to allow the german engineer a satchel

Barashka german combat engineer satchel fix

---

DH_Vehicles/Classes/DH_BT7Cannon.uc
DH_Vehicles/Classes/DH_IS2Cannon.uc
DH_Vehicles/Classes/DH_KV1ECannon.uc
DH_Vehicles/Classes/DH_KV1sCannon.uc
DH_Vehicles/Classes/DH_T3476Cannon.uc
DH_Vehicles/Classes/DH_T3476_42Cannon.uc
DH_Vehicles/Classes/DH_T3476_43Cannon.uc
DH_Vehicles/Classes/DH_T3485Cannon.uc
DH_Vehicles/Classes/DH_T60Cannon.uc

-Coax foley changed
-Coax reload speed improved to 5.5 seconds
-Coax on the t34/76 m41 is 6.5 seconds due to poor ergonomics
Soviet vehicles were notorious for being hard to work with when it comes to infantry support, the coax was on average far longer to reload than its belt fed contemporaries 7.6 seconds at its longest compared to the 6 odd seconds of the belt feds.
Coax reload speed improved to 5.5 seconds, reasoning being its a pan mag that is easily hit up out of the way and then put into place, as compared to the whole feeding process of belt fed machineguns.

Soviet vehicles coax reload changed to 5.5 seconds

---

DarkestHourDev/Maps/DH-Fury_Clash.rom
DarkestHourDev/Maps/DH-Rhine_River_Advance.rom
DarkestHourDev/Maps/DH-Targnon_Advance.rom

Fury Clash:
- Brought Fury Clash up to parity with Fury Advance (features such as new weapons, vehicles, etc., added since Clash was deprecated).
- Increased most objective lockdown timers to 10 minutes from 4-5.
- Added some basic protection minefields behind lines that deactivate as the enemy advances.
Rhine River Advance:
- Fixed doors on a few buildings preventing players from entering.
- Fixed bugged lighting on windmill mover.
- Fixed missing staircase in Honopel objective building.
- Fixed floating tree statics in the forest between Honopel and Refuel Area.
- Fixed bug with the fog ring causing some objects to pop rather than fade in and out of view.
- Removed M45 Quadmount construction from Allies.
- Reduced view distance by about 75 meters to improve client and server …

Small Level Updates and Fixes

---

DH_Engine/Classes/DHPlayer.uc
DH_Engine/Classes/DHSquadReplicationInfo.uc
DH_Interface/Classes/DHDeployMenu.uc
DH_Interface/Classes/DHGUISquadComponent.uc

This makes the following changes:
* The squad panels in the UI will have a different background depending on whether or not the user is in the squad or not.
* Players can now join other squads without losing their non-leader role (i.e., machine-gunner, anti-tank etc.)
* Squad assistants are no longer immediately assigned to be the new squad leader after the squad leader leaves.
* Squad assistants will also not be eligible to be auto-assigned to squad leader if they did not explicitly volunteer to.
The rationale for the ASL changes is that in the current meta, ASLs are usually running logistics, and having an ASL automatically being turned into the SL means that they can no longer build without someone nearby. In the future when we have a dedicated logistics squad, this whole thing can be …

Numerous squad system improvements

---

DH_Vehicles/Classes/DH_HellcatCannonShellHVAP.uc
DH_Vehicles/Classes/DH_ShermanM4A176WCannonShellHVAP.uc
DH_Vehicles/Classes/DH_WolverineCannonShellHVAP.uc

I have changed the penetration of the M93 HVAP round for the 76mm Sherman, M18 Hellcat, and M10 Wolverine. 
The values were taken from a graph from, Terminal Ballistic Data Volume 3, on page 161, (https://i.imgur.com/lAEdkbp.jpg)
This study here: https://apps.dtic.mil/sti/pdfs/AD1045347.pdf 
also supports the upping of the penetration as a table on page 32 states the HVAP round was able to penetrate the front of the panthers turret, but unable to penetrate the front hull, which would be expected from an uncapped slug. 
This handbook: https://archive.org/details/HandbookOfBallisticAndEngineeringDataForAmmunitionVol2/page/n63/mode/2up?q=m93
also supports the penetration numbers, as a shell identical in size (presumably M93, but only described as 1.5 inch tungsten core) penetrates much …

Feature 76 hvap refactor

---

DH_Engine/Classes/DHCommandMenu_SquadManageMember.uc
DH_Engine/Classes/DHPlayer.uc
DH_Engine/Classes/DHSquadMessage.uc
DH_Engine/Classes/DHSquadPromotionRequestInteraction.uc
DH_Engine/Classes/DHSquadReplicationInfo.uc
DH_Interface/Classes/DHContextMenu_SquadMembers.uc
DH_Interface/Classes/DHDeployMenu.uc

When a squad leader promotes a squad member to squad leader, the squad member must now accept it. This is to top malicious or careless squad leaders from just dumping the squad leader role on someone unwilling, potentially invalidating their selected role and putting them in a position of responsibility that they didn't ask for.

[Squads] Squad leader promotions are now opt-in

---

DH_Engine/Classes/DHPlayerReplicationInfo.uc
DH_Engine/Classes/DHSpawnPoint_SquadRallyPoint.uc
DH_Engine/Classes/DHSquadReplicationInfo.uc
DH_Interface/Classes/DHDeployMenu.uc
DH_Interface/Classes/DHGUISquadComponent.uc
DarkestHourDev/Textures/DH_InterfaceArt2_tex.utx

Added indicators to the squad menu to let players know which squads have bad rally point habits.
The indicator will show up if no rallies are placed in 1 minute after:
1. all squad rally points are lost;
2. new squad leader is assigned.

Indicate squads without rally points

---

DH_Engine/Classes/DHArmoredVehicle.uc
DH_Engine/Classes/DHVehicleBurningDamageType.uc
DH_Guns/Classes/DH_PantherturmGun.uc
DH_Vehicles/Classes/DH_BrenCarrierMG.uc
DH_Vehicles/Classes/DH_BrenCarrierTransport.uc
DH_Vehicles/Classes/DH_M16Halftrack.uc
DH_Vehicles/Classes/DH_M3Halftrack.uc
DH_Vehicles/Classes/DH_M45QuadmountMG.uc
DH_Vehicles/Classes/DH_PanzerIVJTank.uc
DH_Vehicles/Classes/DH_SdKfz2519DTransport.uc
DH_Vehicles/Classes/DH_SdKfz251_22Transport.uc
DH_Vehicles/Classes/DH_Sdkfz251MG.uc
DH_Vehicles/Classes/DH_Sdkfz251Transport.uc

Universal Carrier:
- Reworked to be an armored vehicle, for consistency with halftracks.
- Reduced health significantly (from 1500 to 500, now equivalent to halftracks) and added additional hitpoints, the vehicle will still be survivable but can now only take 2-3 AP shells on average, and may catch fire or explode altogether if weakpoints are hit.
- Fixed incorrect Damage Effect offset. 
- Simplified engine hitpoints.
- Increased time it takes for hull-fire to kill passengers and crew, to give a little extra time to bail out.
Sd.Kfz. 251:
- Added fuel hitpoint and fire chance.
- Enabled tank steering as the Sd.Kfz. 251 was capable of this in reality.
- Increased time it takes for hull-fire to kill passengers and crew, to give a little extra time to bail out.
M3A1 Halftrack:
- Added fuel …

Update to APCs/Halftracks

---

DH_Vehicles/Classes/DH_Sdkfz2341Cannon.uc
DH_Vehicles/Classes/DH_Sdkfz2341CannonShellAPCR.uc
DH_Vehicles/Classes/DH_Sdkfz2341CannonShellHE.uc

Sd.Kfz. 234/1 Changes:
- Added new Pzgr. 40 APCR shell as a limited availability ammo option for the 234/1 (replaces the old mixed mag ammo type).
- Renamed cannon shell types appropriately.
- Tweaked 234/1 HE shell to better reflect real life characteristics.

Sd.Kfz. 234/1 Changes

---

DH_Guns/Classes/DH_LeIG18Cannon.uc
DH_Guns/Classes/DH_M116Cannon.uc
DH_Guns/Classes/DH_M1927Cannon.uc

all howitzers (LeIG18, M116, and M1927 guns) have their reload speeds reduced from 10-11 seconds to 6 seconds, and their resupply intervals decreased to 12 seconds (same as the Flak88) from 25  to reflect this new change.

Howitzer reload changes but done right this time

---

DH_Engine/Classes/DHResupplyAttachment_Vehicle.uc
DH_Engine/Classes/DHVehicle.uc

- Created new DHResupplyAttachment_Vehicle class with extended radius of 350 (default is 300).
- Updated DHVehicle to use this attachment class instead. (purpose is to extend the resupply radius of logi trucks).

Extended Resupply Radius of Logistics Trucks

---

DarkestHourDev/Maps/DH-Berezina_Advance.rom
DarkestHourDev/Maps/DH-Cholm_Advance.rom
DarkestHourDev/Maps/DH-St_Marie_du_Mont_Advance.rom

Berezina Advance:
- Added 2 Combat Engineer roles for Soviets.
- Reduced max tanks for both teams, Soviets now have 2 tanks active at once, Germans have 3.
- Made BT7, Panzer III and Panzer IV Ausf. F1 spawns unlimited.
- Reduced max active logi trucks for both teams from 3 to 2.
- Implemented gun limit of 6 for Soviet light AT guns.
Cholm Advance:
- Fixed issue where Axis would bleed tickets while still controlling objectives.
- Improved spawn protection minefield around Axis main spawn.
- Added additional cover to Axis main spawn.
- Disabled Karma collision on all wooden fences.
St Marie du Mont Advance:
- Added new Northwestern and Eastern Road objectives, replacing the old Stable objective.
- Added new spawn protection minefields to both teams.
- Added some additional light cover …

Level updates wolfkraut

---

DH_Engine/Classes/DHPawn.uc
DH_Engine/Classes/DHPawnTouchMessage.uc
DH_Engine/Classes/DHPlayer.uc

When applicable, players can now perform resupply and assisted reload on AT weapons in one key stroke.
This should prevent players from forgetting to double-click the resupply button and run away, which is never a desired outcome.

Combined AT resupply and reload assist into a single action

---

DH_Engine/Classes/DHAxisMarksmanRoles.uc
DH_Engine/Classes/DHAxisSniperRoles.uc
DH_GerPlayers/Classes/DHGEMarksmanRoles.uc
DH_GerPlayers/Classes/DH_12thSSMarksman.uc
DH_GerPlayers/Classes/DH_FJ45Marksman.uc
DH_GerPlayers/Classes/DH_FJMarksman.uc
DH_GerPlayers/Classes/DH_WHMarksman.uc
DH_GerPlayers/Classes/DH_WHMarksmanC.uc
DH_GerPlayers/Classes/DH_WHMarksman_Greatcoat.uc
DH_GerPlayers/Classes/DH_WHMarksman_Greatcoat_Winter.uc
DH_GerPlayers/Classes/DH_WHMarksman_Snow.uc
DH_GerPlayers/Classes/DH_WHMarksman_SnowTwo.uc
DH_GerPlayers/Classes/DH_WHSMarksman_Autumn.uc
DH_GerPlayers/Classes/DH_WKMarksman.uc
DH_GerPlayers/Classes/DH_WSSGreatcoatMarksman.uc
DH_GerPlayers/Classes/DH_WSSGreatcoatMarksman_Winter.uc
DH_GerPlayers/Classes/DH_WSSMarksman.uc
DH_GerPlayers/Classes/DH_WSSMarksman_Autumn.uc
DH_GerPlayers/Classes/DH_WSSMarksman_Snow.uc

Historically, there was no distinction between snipers with the ZF39 (4x power) scope and those with the ZF41 (1.5x power) scope, however the ZF41 was used in a role much similar to designated marksmen today, and the ZF41 was far more numerous than the ZF39
https://www.youtube.com/watch?v=sBstpqUAniw (citation)
Proposed changes would be the reduction of higher tier snipers (those with zf39 and zf4 scopes), addition of a new "marksman" role, and a replacement for those that were reduced, I.E changing a map from 2 snipers to 1, but then adding a marksman.
The marksman role is named as such in code and with standard naming conventions, but within the native names for the faction, it is still named "scharfschütze" as there was no NAMED distinction within the Wehrmacht and SS, only one with …

Additon of "marksman" role for axis

---

DarkestHourDev/Maps/DH-Armored_Raid_to_Bastogne_Advance.rom
DarkestHourDev/Maps/DH-Maupertus_Advance.rom
DarkestHourDev/Maps/DH-Pointe_Du_Hoc_Push.rom
DarkestHourDev/Maps/DH-Poteau_Ambush_Advance.rom

Maupertus Advance:
- Fixed broken map boundaries.
- Fixed Axis initial spawns being swapped.
Pointe du Hoc:
- Fixed objective clear behavior being broken.
Poteau Ambush:
- Updated minefields.
- Rebalanced Danger Zone influences of objectives.
Armored Raid to Bastogne:
- Fixed erroneous collision settings on static bush line near map center.

Level Updates and Fixes:

---

DH_Weapons/Classes/DH_G98Attachment.uc

- Applied an offset to the G98 muzzle flash to resolve an issue with the flash effect appearing several inches in front of the barrel.

G98 Muzzle Flash Fix

---

DH_Engine/Classes/DHWeapon.uc

This fixes a visual bug where sprinting animimations take over melee "hold" animations for melee only weapons (like shovels and maces).
Also fixed an instance where it's assumed that melee is always the second fire mode.

Fixed a bug where some melee anims wouldn't play correctly during sprint

---

DH_GerPlayers/Classes/DH_VSAssault.uc
DH_GerPlayers/Classes/DH_VSRifleman.uc

This change caused issues with Berlin maps as VS roles were often the only unlimited ones available, a situation could exist where a player created a squad and could not choose any role. Other solutions such as giving infinite Corporal roles to compensate do not make sense. Additionally, the Volkssturm historically had the same standard squad structure as the Heer and SS and operated independently, a Volkssturm squad would be lead by Volkssturm, not other Heer or SS NCOs.

Reverted Squad Leader Role Restrictions for VS Rifleman and Assault.

---

DH_Engine/Classes/DHPawn.uc

Fixes #473
An ancient RO bug that prevented players from leaning and hipfiring out of cover.

Fixed bullets not originating from the gun when leaning and hipfiring

---

DH_Engine/Classes/DHPlayer.uc
DH_Engine/Classes/DHPlayerSession.uc
DH_Engine/Classes/DarkestHourGame.uc

Fixes #1663
Other changes:
- Player score managers now persist between client sessions.
- Moved code for saving and restoring sessions into the `DHPlayerSession` class.

Fixed a bug where players lose score after rejoining a match

---

DH_Construction/Classes/DHConstruction_PlatoonHQ.uc
DH_Construction/Classes/DHConstruction_SupplyCache.uc
DH_Construction/Classes/DHConstruction_VehiclePool.uc
DH_Engine/Classes/DHAntiVehicleProjectile.uc
DH_Engine/Classes/DHArtilleryShell.uc
DH_Engine/Classes/DHConstruction.uc
DH_Engine/Classes/DHMortarProjectile.uc
DH_Engine/Classes/DHThrowableExplosiveProjectile.uc

Constructions can end up with their origin point wedged under the terrain, which makes them untraceable and immune to blast damage. This is fixed by changing the trace target to a custom location instead of origin.
Fixes #314

Fixed a bug where constructions are sometimes immune to explosions

---

DH_Construction/Classes/DHConstruction_Sandbags.uc

- Partially built sandbags will now live indefinitely. Given that partially constructed sandbags can potentially be more useful in some scenarios than fully built ones, this allows players the choice for instance of if they want a half wall or full wall, or covered bunker vs. open bunker.

Removed stagnation death from sandbags:

---

DH_Engine/Classes/DHAutomaticFire.uc
DH_Engine/Classes/DHProjectileFire.uc
DH_Engine/Classes/DHProjectileWeapon.uc
DH_Engine/Classes/DHWeaponFire.uc

This fixes a visual bug where some guns (G43, G41, MP40, and others) have heir bolt slowly slide into position when the magazine is emptied.
- [Optimization] Disabled component animation update calls on the server in `ModeDoFire()`.
- Fixed MG belt bullets being out of sync with ammo count in multiplayer.

Fixed "last fire" animations not working in multiplayer

---

DH_Vehicles/Classes/DH_ShermanM4A3105CannonShellHEAT.uc
DH_Vehicles/Classes/DH_ShermanTank_M4A3105_Howitzer.uc
DH_Vehicles/Classes/DH_StuH42Cannon.uc
DH_Vehicles/Classes/DH_StuH42CannonShellHEAT.uc
DH_Vehicles/Classes/DH_StuH42Destroyer.uc
DH_Vehicles/Classes/DH_Stug3GDestroyer.uc

Sherman 105:
- Reduced damage and damage radius of 105 HEAT shell to old values. This projectile has a large HE filler, but it's still a shaped charge, not HE-frag. Even the old values are possibly overperforming, but I suppose 11.5 meter lethal radius is acceptable.
- Fixed some spacing errors in the comments of the Sherman 105.
StuH42:
- Reverted damage and impact damage to old values for StuH42 HEAT shell (matches Sherman 105, which is a roughly equivelant shell in performance). Also added comment correcting the previously erroneous filler value with source.
- Updated native names for StuH projectiles. StuH 42 fired Feld Haubitze Granate for HE (and this was even reflected in the smoke shell name already) and fires Gr.39 for HEAT (distinct from the Gr.38 used in 7.5cm guns and possibly …

Update to Sherman 105 and StuH42:

---

DH_Vehicles/Classes/DH_50CalDamType.uc
DH_Vehicles/Classes/DH_50CalVehicleBullet.uc
DH_Weapons/Classes/DH_PTRDBullet.uc
DH_Weapons/Classes/DH_PTRDDamType.uc

.50 Cal:
- Reduced damage modifier to recreate damage output prior to commit b787a8d. Now requires approximately 50 rounds to kill a tank (unless hitting an ammo rack, or RNG shrapnel damage) vs. 10 rounds from the above mentioned commit. 
PTRD: 
- Same as above, reduced damage modifiers to match old damage output. This does significantly reduce the effectiveness of the PTRD, though, and may require further tweaking in the future. To compensate, I slightly increased fire chance modifiers on the round, as it was an incendiary bullet (new values are closer to German 20mm AP (which is solid shot and doesn't actually have any incendiary load).

Fixed AP Bullet Damage Modifiers

---

DH_Vehicles/Classes/DH_JagdpantherCannonShell.uc

The JPV was utilizing the damage of the tiger 1 while being the exact same gun as the tiger 2, this change only switches the damage to be identical to the tiger 2's.

Damage Change

---

DarkestHourDev/Maps/DH-Armored_Wacht_am_Rhein_Advance.rom
DarkestHourDev/Maps/DH-Bremoy_Advance.rom
DarkestHourDev/Maps/DH-Gran_Advance.rom
DarkestHourDev/Maps/DH-Kriegstadt_Push_USA.rom

Bremoy:
- Optimized terrain and deco layers, hopefully increasing performance slightly.
- Added small +2% team balance ratio towards Allies.
- Reworked all objective Danger Zone influences.
- Removed ticket bleed from first objective.
- Reduced Panther max spawns from infinite to 3.
- Reduced Sherman MkII respawn timer from 220 seconds to 180.
- Increased Firefly max spawns from 2 to 3 and reduced respawn timer to 180 seconds.
- Increased Stuart spawns from 1 to 5 and reduced respawn timer to 200 seconds.
- Increased max AT guns for Allies of all types from 1 to 2 and reduced respawn timer to 120 seconds.
- Added Wolverine SP (British M10) with 3 spawns to Allies.
Kriegstadt Push USA:
- Recreated the classic 29th style US faction version.
Gran Advance:
- Infantry version of popular …

Level Updates and Event Maps

---

DH_Engine/Classes/DHVehicleWeaponPawn.uc
UCore/Classes/URotator.uc

An ancient bug where turrets and guns auto-rotate if they were fiddled with by another player before you enter them.
The solution is a little hacky ([see comments](https://github.com/DarklightGames/DarkestHour/blob/ba9f905ca20190d8248fb45092caa90c38df2b92/DH_Engine/Classes/DHVehicleWeaponPawn.uc#L760-L764)), but i haven't found a better alternative because most of the aim handling is obscured by the engine.
1. Start a server with two clients
2. Enter a tank and rotate its turret on client 1.
3. Enter the same turret on client 2.
4. The gun will auto-rotate itself to the default position (or last position used by client 2).

Fixed turrets and cannons spontaneously rotating when entering them

---

DarkestHourDev/Maps/DH-Klin1941_Advance.rom
DarkestHourDev/Maps/DH-Kryukovo_Push.rom
DarkestHourDev/Maps/DH-Winter_Stalemate_Clash.rom

Klin 1941:
- Increased Axis ticket modifier by 2.
- Reduced Panzer IV F1 respawn timer from 120 to 90 seconds.
- Increased BT7 respawn timer from 100 to 120 seconds.
Kryukovo:
- Added setup phase with a 60 second timer and new blocking boundaries.
- Increased round time from 20 to 25 minutes.
- Reduced T34/76 respawn timer from 180 to 90 seconds.
- Increased max T34/76 spawns from 3 to 4.
- Increased max Panzer IIIj spawns from 3 to 4.
- Gave Soviets a single very strong artillery strike and added a static radio near their initial spawn point.
- Added spawn protection/noarty minefields to Axis spawns.
- Increased Axis artillery strikes from 1 to 3, but reduced their effectiveness.
- Fixed some misc. bugs (terrain holes, floating trees).
- Disabled Karma collision on fences and small …

Event Level Updates

---

DH_Engine/Classes/DHMortarVehicleWeaponPawn.uc
DH_Engine/Classes/DHPawn.uc
DH_Engine/Classes/DHProjectileFire.uc
DH_Weapons/Classes/DH_M2MortarVehicleWeaponPawn.uc
DarkestHourDev/Animations/DHCharactersGER_anm.ukx
DarkestHourDev/Animations/DH_Mortars_1st.ukx

* Fixed jittery and out of sync character animations on mortars.
* US M2 mortar now shows a correct shell model when firing in first person.
* Reverted the rates for `deploy_fire`, `flinch_return`, and `deploy` animations to values before commit 25bfbc278a1af20b28d72d8db83c1703aa816285. This fixed the issue where the mortar weapon and character anims were out of sync.
* Lowered the rates for `deploy_idle` animations to 0.2 for performance reasons (this prevents triggering `AnimEnd` too often).
* Changed bone naming and hierarchy for shell bones.
* Renamed bone `Bone01` to `Muzzle` and centered it on the barrel (the bone is not used for anything, it was just irritating me).
* Removed unused `fire_HE` and `fire_WP` animations.

Fixed a number of issues with mortar animations

---

DH_Engine/Classes/DHVehicleCannon.uc
DH_Vehicles/Classes/DH_PanzerIIILCannon_Camo.uc
DH_Vehicles/Classes/DH_PanzerIIINCannon_CamoOne.uc
DH_Vehicles/Classes/DH_PanzerIVGEarlyCannon.uc
DH_Vehicles/Classes/DH_PanzerIVGLateCannon.uc

- DHVehicleCannon (turret) schurzen now uses the same behavior as DHArmoredVehicle (hull).
- Turret schurzen now blocks AP bullets (PTRD) and HE shells under 8.5cm in caliber.
- Turret schurzen now only defeats HEAT projectiles if the angle of incidence is over 45 degrees.
- Added new bHasAddedRearArmor variable and applied this to the respective German vehicles that have it (Panzer IV and late Panzer III models). This means that the rear of these vehicle's turrets will now also correctly benefit from schurzen.

Fixed inconsistencies between DHArmoredVehicle and DHVehicleCannon:

---

DH_Engine/Classes/DHSquadReplicationInfo.uc

Done to ensure that squad leaders can't be blamed for bad squad names set by their predecessors.

Squad name is reset to default when a new squad leader is assigned

---

DarkestHourDev/Maps/DH-Cheneux_Advance.rom
DarkestHourDev/Maps/DH-Reichswald_Advance.rom

Cheneux:
- Fixed leaking objective volume that caused Axis to be unable to place rallies and made the first objective essentially uncapturable.
Reichswald:
- Added new map overview from Seven.
- Fixed NoSnow volumes not working on the HQ Bunker objective.
- Fixed missing gun limits for AT Light and AA Light constructions (previously was applying to medium versions that aren't present on the map)
- Reworked a few mine volumes to be more intuitive.
- Updated minefield warning signs to match the above change.
- Increased Axis tickets slightly.
- Rewrote unit descriptions for both teams.

Chenux and Reichswald Fixes

---

DH_Weapons/Classes/DH_FG42Fire.uc

- Curve was flattened somewhat. Previous recoil curve was extremely aggressive and would leave you aiming at the sky after anything more than a 3 round burst.
- Reduced MaxVert and Horizontal recoil values.
- Changed the modifiers for prone, bipod and rested to account for the lower overall recoil. These positions are now actually less controllable than before, but still offer a meaningful advantage over standing.

Tweaked FG42 Recoil:

---

DH_Effects/Classes/DHBulletHitEffect.uc
DH_Effects/Classes/DHBulletHoleDev.uc
DarkestHourDev/Textures/DH_FX_Tex.utx

-Added DevImpact to DH_FX_Tex.Effects
-Added DHBulletHoleDEV
-Made EST_Custom05 into a developer material that displays a purple square when a bullet impacts it
LifeSpan is set to 30 and overrides the decal stay time setting, does not affect other decal stay times
Idea behind this addition, is to add a dev specific material that makes the bullet impacts far more visible that before.
Reasoning for this is that it is quite hard to see your bullet impacts or spray patterns when testing out weapons, this change would make them more visible, allowing you to better understand your spread or recoil on the weapon.
https://github.com/user-attachments/assets/7d0a59f6-143c-47d6-8c49-dc2f0627db4e

Added Developer Hit Material

---

.gitignore
.vscode/extensions.json
.vscode/tasks.json

Added tasks for building (with problem matching) and launching the game in VS Code.
- **Build**: Compiles the game. Compiler errors/warnings are sent to the "Problems" view. *Set as default build task.*
- **Build with Parameters**: Same as **Build** but shows a prompt before compiling for passing additional parameters to `make.py`.
- **Run**: Launches the game.
- **Run Map**: Quick loads a selected map.
- **Run Default Map**: Quick loads "Target Range". Added as a shortcut to skip the map selection prompt  (would be nice to make the default map configurable in the future).
- **Build and Run**: Combines **Build** and **Run**.
- **Build and Run Map**: Combines **Build** and **Run Map**.
- **Build and Run Default Map**: Combines **Build** and **Run Default Map**. *Set as default test task.* …

VS Code Tasks
